{% set name = "ispyb" %}
{% set version = "7.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/ispyb-{{ version }}.tar.gz
  sha256: 9dabbe3aa4d8a05875240c0cf8b3de5f6bc0d3fc02fe9e785c81d8ecdeb1fe50

build:
  number: 0
  noarch: python
  entry_points:
    - ispyb.job = ispyb.cli.job:main
    - ispyb.last_data_collections_on = ispyb.cli.last_data_collections_on:main
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - mysql-connector-python <=8.0.29
    - python >=3.6
    - sqlalchemy <2
    - tabulate

test:
  imports:
    - ispyb
    - ispyb.cli
    - ispyb.connector
    - ispyb.connector.mysqlsp
    - ispyb.connector.ws
    - ispyb.interface
    - ispyb.sp
    - ispyb.ws
  commands:
    - pip check
    - ispyb.job --help
    - ispyb.last_data_collections_on --help
  requires:
    - pip

about:
  home: https://pypi.org/project/ispyb/
  summary: Python package to access ISPyB database
  description: |
    This package provides a python interface to ISPyB.
    It can access the ISPyB database directly or (in
    future versions) run on top of the official ISPyB
    webservices API.
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE.md
  dev_url: https://github.com/DiamondLightSource/ispyb-api
  doc_url: https://ispyb.readthedocs.io/

extra:
  recipe-maintainers:
    - HorstmannA
    - stuartcampbell
    - KarlLevik
    - anthchirp
    - rjgildea
